In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [39]:
import os

os.getcwd()

'd:\\Main project\\credit-default-risk\\notebooks'

In [40]:
os.listdir("../data")

['processed', 'raw']

In [41]:
os.listdir("../data/raw")

['credit_risk_dataset.csv']

In [42]:
import os
os.listdir("../data/raw")

['credit_risk_dataset.csv']

In [43]:

df = pd.read_csv("../data/raw/credit_risk_dataset.csv")
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [45]:
df.shape

(32581, 12)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

In [47]:
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [49]:
df["loan_status"].value_counts(dropna=False)

loan_status
0    25473
1     7108
Name: count, dtype: int64

In [50]:
df["cb_person_default_on_file"].value_counts(dropna=False)

cb_person_default_on_file
N    26836
Y     5745
Name: count, dtype: int64

In [52]:
df["loan_status"].dtype

dtype('int64')

In [54]:
df["loan_status"].isna().sum()

np.int64(0)

Credit Risk EDA

In [55]:
# creating a copy
df_eda = df.copy()

In [56]:
# checking how defaults differ by a key feature
pd.crosstab(
    df_eda["cb_person_default_on_file"],
    df_eda["loan_status"],
    normalize="index"
)

loan_status                       0         1
cb_person_default_on_file
N                          0.816068  0.183932
Y                          0.621932  0.378068

The above table shows:

No prior default (N)
  Default rate ≈ 18.4%

Prior default (Y)
  Default rate ≈ 37.8%

Meaning customers with proir default are about twice as likely to default again in this dataaset

In [57]:
# Identyfying numerical features
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
num_cols

Index(['person_age', 'person_income', 'person_emp_length', 'loan_amnt',
       'loan_int_rate', 'loan_status', 'loan_percent_income',
       'cb_person_cred_hist_length'],
      dtype='object')

In [61]:
# identyfying categorical features
cat_cols = df.select_dtypes(include=["object"]).columns
cat_cols

Index(['person_home_ownership', 'loan_intent', 'loan_grade',
       'cb_person_default_on_file'],
      dtype='object')

In [ ]:
# comparing distribution of a numerical feature by loan status

df.groupby("loan_status")["cb_person_cred_hist_length"].describe()

               count      mean       std  min  25%  50%  75%   max
loan_status
0            25473.0  5.837475  4.040900  2.0  3.0  4.0  8.0  30.0
1             7108.0  5.685003  4.103208  2.0  3.0  4.0  8.0  30.0

According to the above analysis Defaulters (loan_status = 1) tend to have lower credit history length (cb_person_cred_hist_length) compared to non-defaulters, which suggests less established credit behavior.

In [62]:
df[num_cols].isnull().sum(), df[cat_cols].isnull().sum()

(person_age                       0
 person_income                    0
 person_emp_length              895
 loan_amnt                        0
 loan_int_rate                 3116
 loan_status                      0
 loan_percent_income              0
 cb_person_cred_hist_length       0
 dtype: int64,
 person_home_ownership        0
 loan_intent                  0
 loan_grade                   0
 cb_person_default_on_file    0
 dtype: int64)

In [64]:
# impute missing values

# Numerical: median
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())


# Categorical: mode
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [65]:
df.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [70]:
cat_cols = df.select_dtypes(include=["object"]).columns
cat_cols

Index([], dtype='object')

In [67]:
# Encoding binary categorical features
df["cb_person_default_on_file"] = df["cb_person_default_on_file"].map({"N": 1, "Y": 0})

In [71]:
# One-hot encoding remaining categoricals 
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   person_age                   32581 non-null  int64
 1   person_income                32581 non-null  int64
 2   person_emp_length            32581 non-null  float64
 3   loan_amnt                    32581 non-null  int64
 4   loan_int_rate                32581 non-null  float64
 5   loan_status                  32581 non-null  int64
 6   loan_percent_income          32581 non-null  float64
 7   cb_person_default_on_file    32581 non-null  int64
 8   cb_person_cred_hist_length   32581 non-null  int64
 9   person_home_ownership_OTHER  32581 non-null  bool
 10  person_home_ownership_OWN    32581 non-null  bool
 11  person_home_ownership_RENT   32581 non-null  bool
 12  loan_intent_EDUCATION        32581 non-null  bool
 13  loan_intent_HOMEIMPROVEMENT  32581 non-null  bool
 14  loan_intent_MEDICAL          32581 non-null  bool
 15  loan_intent_PERSONAL         32581 non-null  bool
 16  loan_intent_VENTURE          32581 non-null  bool
 17  loan_grade_B                 32581 non-null  bool
 18  loan_grade_C                 32581 non-null  bool
 19  loan_grade_D                 32581 non-null  bool
 20  loan_grade_E                 32581 non-null  bool
 21  loan_grade_F                 32581 non-null  bool
 22  loan_grade_G                 32581 non-null  bool
dtypes: bool(14), float64(3), int64(6)
memory usage: 2.7 MB

# Train/test split

In [74]:
from sklearn.model_selection import train_test_split

x = df.drop("loan_status", axis=1)
y = df["loan_status"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [75]:
# Verifying the split
y_train.value_counts(normalize=True), y_test.value_counts(normalize=True)

(loan_status
 0    0.781845
 1    0.218155
 Name: proportion, dtype: float64,
 loan_status
 0    0.781801
 1    0.218199
 Name: proportion, dtype: float64)

# Interpretation for the above veryfication

-Train default rate: ~21.82%

-Test default rate: ~21.82%

# Training the baseline model(Logistic Regression with scaling)

Doing this because Logistic Regression is scale-sensitive. Tree-based models are not

In [80]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

log_reg = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        solver="lbfgs"
    ))
])

In [81]:
log_reg.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=2000))])

# Evaluation Metrics

In [82]:
# Evaluate ROC-AUC
from sklearn.metrics import roc_auc_score

y_pred_proba = log_reg.predict_proba(x_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_pred_proba)
roc_auc

0.8712062928134778

In [83]:
#Classification report
from sklearn.metrics import classification_report
y_pred = log_reg.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.82      0.87      5095
           1       0.55      0.78      0.65      1422

    accuracy                           0.81      6517
   macro avg       0.74      0.80      0.76      6517
weighted avg       0.85      0.81      0.82      6517

In [84]:
# Train LightGBM model
import lightgbm as lgb

lgb_model = lgb.LGBMClassifier(
    objective="binary",
    n_estimators=500,
    learning_rate=0.05,
    num_leaves=31,
    max_depth=-1,
    min_data_in_leaf=100,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

In [ ]:
# Train the model
lgb_model.fit(x_train, y_train)

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
[LightGBM] [Info] Number of positive: 5686, number of negative: 20378
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002361 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 924
[LightGBM] [Info] Number of data points in the train set: 26064, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.218155 -> initscore=-1.276449
[LightGBM] [Info] Start training from score -1.276449

LGBMClassifier(colsample_bytree=0.8, learning_rate=0.05, min_data_in_leaf=100,
               n_estimators=500, objective='binary', random_state=42,
               subsample=0.8)

In [86]:
# Evaluate ROC-AUC for LightGBM

y_pred_proba_lgb = lgb_model.predict_proba(x_test)[:, 1]
roc_auc_lgb = roc_auc_score(y_test, y_pred_proba_lgb)

roc_auc_lgb

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100

0.9524776089738016

In [87]:
# Classification report for LightGBM
y_pred_lgb = lgb_model.predict(x_test)
print(classification_report(y_test, y_pred_lgb))

[LightGBM] [Warning] min_data_in_leaf is set=100, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=100
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      5095
           1       0.96      0.73      0.83      1422

    accuracy                           0.93      6517
   macro avg       0.95      0.86      0.89      6517
weighted avg       0.94      0.93      0.93      6517

# Training XGBoost

In [88]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    objective="binary:logistic",
    n_estimators=500,
    learning_rate=0.05,
    max_depth=5,
    min_child_weight=100,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="auc",
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=100, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=500,
              n_jobs=-1, num_parallel_tree=None, ...)

In [89]:
# Evaluating ROC-AUC for XGBoost

y_pred_proba_xgb = xgb_model.predict_proba(x_test)[:, 1]
roc_auc_xgb = roc_auc_score(y_test, y_pred_proba_xgb)

roc_auc_xgb

0.9311464729906735

In [90]:
# Classification report for XGBoost
y_pred_xgb = xgb_model.predict(x_test)
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.92      0.99      0.95      5095
           1       0.94      0.70      0.80      1422

    accuracy                           0.93      6517
   macro avg       0.93      0.84      0.88      6517
weighted avg       0.93      0.93      0.92      6517

In [93]:
import os
import joblib

os.makedirs("../models", exist_ok=True)
joblib.dump(lgb_model, "../models/lightgbm_credit_default.pkl")

['../models/lightgbm_credit_default.pkl']